// Expo config plugin: adopt the iOS UIScene life cycle.
//
// iOS 27 hard-enforces the UIScene life cycle. The Expo SDK 56 template `AppDelegate.swift` creates
// the app window the legacy way (inside `didFinishLaunchingWithOptions`), which iOS 27 terminates
// on launch with EXC_BREAKPOINT in `_UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`
// (white screen, then crash).
//
// `ios/` is gitignored and regenerated by `expo prebuild`, so the fix cannot live as a hand-edit in
// `ios/`. This plugin re-applies it on every prebuild:
//   1. AppDelegate.swift — stop creating the window there; vend a UISceneConfiguration; add a
//                          SceneDelegate that owns the window and starts React Native into it.
//   2. Info.plist        — declare a complete UIApplicationSceneManifest naming that delegate.
//
// The source transform lives in ./iosSceneTransform.js (pure + unit-tested). It throws loudly if
// the Expo template shape changes, rather than silently producing a crashing app.
//
// Remove this plugin once Expo ships native UIScene support (tracking: expo/expo#46664).

const { withAppDelegate, withInfoPlist, createRunOncePlugin } = require('expo/config-plugins');
const { transformAppDelegate, SCENE_MANIFEST } = require('./iosSceneTransform');

const withIosSceneLifecycle = (config) => {
  config = withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[withIosSceneLifecycle] Expected a Swift AppDelegate, got "${cfg.modResults.language}".`
      );
    }
    cfg.modResults.contents = transformAppDelegate(cfg.modResults.contents);
    return cfg;
  });

  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = SCENE_MANIFEST;
    return cfg;
  });

  return config;
};

module.exports = createRunOncePlugin(withIosSceneLifecycle, 'withIosSceneLifecycle', '1.0.0');
